version: 2
jobs:
  build:
    working_directory: ~/sms-notifier
    docker:
      - image: circleci/openjdk:11.0.1-jdk-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: ~/sms-notifier-{{ checksum "pom.xml" }}
      - run: mvn clean -Dtest=Checker test
workflows:
   version: 2
   commit:
     jobs:
      - build
   nightly:
     triggers:
       - schedule:
          # 9am UTC
          cron: "00 08 * * 1-5"
          filters:
            branches:
              only: master
     jobs:
       - build
